const APP_VERSION='v0.7.2';
const SUPABASE_URL='https://mdnttasmkgnaxzkxqaks.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_Ftv4e-vlXgWEs2aV7BFSTw_CcX1DVT9';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);

const fmtEUR=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n||0));
const fmtNum=(n,d=1)=>new Intl.NumberFormat('it-IT',{minimumFractionDigits:d,maximumFractionDigits:d}).format(Number(n||0));
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const norm=s=>String(s||'').trim();
const monthNames=['Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre'];
const today=new Date();
const ym=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
let state={view:'home',month:ym(today),edit:null,editType:null,loading:true,tab:'daily',message:'',authMode:'login'};
let session=null;
let data={clients:[],projects:[],activities:[],entries:[],monthly:[],billingHeaders:[],profiles:[]};

function monthLabel(m){const [y,mo]=m.split('-').map(Number);return `${monthNames[mo-1]} ${y}`}
function periodParts(m=state.month){const [year,month]=m.split('-').map(Number);return {year,month}}
function changeMonth(delta){let [y,m]=state.month.split('-').map(Number);m+=delta;if(m<1){m=12;y--}if(m>12){m=1;y++}state.month=`${y}-${String(m).padStart(2,'0')}`;render()}
function setMsg(msg){state.message=msg;render();setTimeout(()=>{if(state.message===msg){state.message='';render()}},3500)}
function clientById(id){return data.clients.find(c=>c.id===id)}
function projectById(id){return data.projects.find(p=>p.id===id)}
function activityById(id){return data.activities.find(a=>a.id===id)}
function clientName(id){return clientById(id)?.name||'Senza cliente'}
function projectName(id){return projectById(id)?.name||''}
function activityName(id){return activityById(id)?.name||''}
function entryRate(e){return Number(e.daily_rate_snapshot ?? clientById(e.client_id)?.daily_rate ?? 0)}
function entryStd(e){return Number(e.standard_hours_snapshot ?? clientById(e.client_id)?.standard_hours ?? 8) || 8}
function dailyAmount(e){return entryRate(e)/entryStd(e)*Number(e.hours||0)}
function dailyDays(e){return Number(e.hours||0)/entryStd(e)}
function rowsForMonth(){return data.entries.filter(e=>String(e.entry_date||'').startsWith(state.month))}
function monthlyRows(){const {year,month}=periodParts();return data.monthly.filter(e=>Number(e.year)===year&&Number(e.month)===month)}
function totals(){let h=0,a=0;rowsForMonth().forEach(e=>{h+=Number(e.hours||0);a+=dailyAmount(e)});monthlyRows().forEach(e=>a+=Number(e.amount||0));return {hours:h,days:h/8,amount:a}}
function metricLine(hours,amount){return `${fmtNum(hours,1)} h <span class="dot">·</span> ${fmtNum(Number(hours||0)/8,1)} gg/u <span class="dot">·</span> ${fmtEUR(amount)}`}
function monthlyMetricLine(amount){return `Una tantum <span class="dot">·</span> ${fmtEUR(amount)}`}
function groupSummary(){const map={};
  rowsForMonth().forEach(e=>{const k=`${e.client_id}|${e.project_id||''}|daily`; if(!map[k]) map[k]={client_id:e.client_id,project_id:e.project_id,type:'daily',hours:0,amount:0}; map[k].hours+=Number(e.hours||0); map[k].amount+=dailyAmount(e)});
  monthlyRows().forEach(e=>{const k=`${e.client_id}|${e.project_id||''}|monthly`; if(!map[k]) map[k]={client_id:e.client_id,project_id:e.project_id,type:'monthly',hours:null,amount:0}; map[k].amount+=Number(e.amount||0)});
  return Object.values(map).sort((a,b)=>`${clientName(a.client_id)}|${projectName(a.project_id)||''}`.localeCompare(`${clientName(b.client_id)}|${projectName(b.project_id)||''}`));
}
function fiscoText(r){if(r.type==='daily') return `Consulenza - ${monthLabel(state.month)} - Cliente/Progetto: ${projectName(r.project_id)||clientName(r.client_id)} | Giorni: ${fmtNum((r.hours||0)/8,1)}`; return `Consulenza - ${monthLabel(state.month)} - Cliente/Progetto: ${projectName(r.project_id)||clientName(r.client_id)}`}
function headerForClient(client_id){const {year,month}=periodParts();return data.billingHeaders.find(h=>h.client_id===client_id&&Number(h.year)===year&&Number(h.month)===month)}
function headerStatus(client_id){return headerForClient(client_id)?.status||'to_invoice'}
function statusLabel(s){return ({to_invoice:'Da fatturare',invoice_issued:'Fattura emessa',collected:'Incassato',excluded:'Escluso'})[s]||'Da fatturare'}
function statusClass(s){return ({to_invoice:'orange',invoice_issued:'blue',collected:'green',excluded:'gray'})[s]||'orange'}
function go(v){state.view=v;state.edit=null;state.editType=null;render()}

async function init(){
  const res=await sb.auth.getSession();
  session=res.data.session;
  if(session) await fetchAll();
  state.loading=false; render();
  sb.auth.onAuthStateChange(async(_event,newSession)=>{session=newSession; if(session){await fetchAll();state.view='home'} else {data={clients:[],projects:[],activities:[],entries:[],monthly:[],billingHeaders:[],profiles:[]};state.view='login';state.authMode='login'} render();});
}
async function fetchAll(){
  state.loading=true; render();
  await ensureUserProfileFromMetadata();
  const tables=[
    ['clients','clients'],['projects','projects'],['activities','activities'],
    ['user_profiles','profiles'],['timesheet_entries','entries'],['monthly_compensations','monthly'],['billing_headers','billingHeaders']
  ];
  for(const [table,key] of tables){
    let q=sb.from(table).select('*');
    if(table==='timesheet_entries') q=q.order('entry_date',{ascending:false});
    else if(table==='monthly_compensations') q=q.order('year',{ascending:false}).order('month',{ascending:false});
    else q=q.order('created_at',{ascending:true});
    const {data:rows,error}=await q;
    if(error){console.error(table,error); setMsg(`Errore caricamento ${table}: ${error.message}`); data[key]=[];} else data[key]=rows||[];
  }
  state.loading=false;
}
async function reload(){await fetchAll();render()}

async function ensureUserProfileFromMetadata(){
  if(!session?.user) return;
  try{
    const {data:existing,error:selectError}=await sb.from('user_profiles').select('*').eq('user_id',session.user.id).maybeSingle();
    if(selectError){console.warn('user_profiles select',selectError);return;}
    if(existing) return;
    const m=session.user.user_metadata||{};
    const payload={
      first_name:m.first_name||'',
      last_name:m.last_name||'',
      company_name:m.company_name||'',
      vat_number:m.vat_number||'',
      email:session.user.email||m.email||''
    };
    const {error}=await sb.from('user_profiles').insert(payload);
    if(error) console.warn('user_profiles insert',error);
  }catch(e){console.warn('ensureUserProfileFromMetadata',e)}
}


function appShell(content){return `<div class="app"><div class="header"><div class="brand"><img class="brandIcon" src="assets/totime-icon-dark.png" alt="TOTIME"><div><div class="brandName">TOTIME</div><div class="brandTagline">Il tuo tempo. Il tuo valore.</div></div></div><button class="iconbtn" onclick="go('settings')" title="Configurazione">⚙</button></div>${state.message?`<div class="card small">${esc(state.message)}</div>`:''}${content}<div class="small" style="text-align:center;margin:24px 0 4px">${APP_VERSION} · Database Edition</div></div>${nav()}`}
function nav(){const items=[['home','Home'],['timesheet','Timesheet'],['summary','Riepilogo'],['billing','Fatture'],['settings','Config']];return `<div class="nav">${items.map(([v,l])=>`<button class="${state.view===v?'active':''}" onclick="go('${v}')">${l}</button>`).join('')}</div>`}
function monthSelector(){return `<div class="month"><button onclick="changeMonth(-1)">‹</button><strong>${monthLabel(state.month)}</strong><button onclick="changeMonth(1)">›</button></div>`}
function loadingView(){return `<div class="app"><div class="brand"><img class="brandIcon" src="assets/totime-icon-dark.png" alt="TOTIME"><div><div class="brandName">TOTIME</div><div class="brandTagline">Il tuo tempo. Il tuo valore.</div></div></div><div class="card"><h1>Caricamento...</h1><p class="sub">Connessione al database Supabase.</p></div></div>`}
function loginView(){return `<div class="app"><div class="brand" style="margin-top:24px"><img class="brandIcon" src="assets/totime-icon-dark.png" alt="TOTIME"><div><div class="brandName">TOTIME</div><div class="brandTagline">Il tuo tempo. Il tuo valore.</div></div></div><div class="card"><h1>Accesso</h1><p class="sub">Accedi per salvare clienti, consuntivi, fatture e incassi nel database.</p>${state.message?`<p class="small">${esc(state.message)}</p>`:''}<form class="form" onsubmit="signIn(event)"><div class="field"><label>Email</label><input name="email" type="email" autocomplete="email" required></div><div class="field"><label>Password</label><input name="password" type="password" autocomplete="current-password" required></div><button class="primary">Accedi</button><button type="button" class="secondary" onclick="state.view='register';state.message='';render()">Registrati</button></form></div></div>`}
function registerView(){return `<div class="app"><div class="brand" style="margin-top:24px"><img class="brandIcon" src="assets/totime-icon-dark.png" alt="TOTIME"><div><div class="brandName">TOTIME</div><div class="brandTagline">Il tuo tempo. Il tuo valore.</div></div></div><div class="card"><h1>Crea account TOTIME</h1><p class="sub">Inserisci i dati del tuo profilo. Li useremo per collegare configurazioni, consuntivi e fatturazione al tuo account.</p>${state.message?`<p class="small">${esc(state.message)}</p>`:''}<form class="form" onsubmit="signUpDetailed(event)"><div class="field"><label>Nome</label><input name="first_name" autocomplete="given-name" required></div><div class="field"><label>Cognome</label><input name="last_name" autocomplete="family-name" required></div><div class="field"><label>Azienda / Ragione sociale</label><input name="company_name" autocomplete="organization" required></div><div class="field"><label>P.IVA</label><input name="vat_number" inputmode="numeric" autocomplete="off" required></div><div class="field"><label>Email</label><input name="email" type="email" autocomplete="email" required></div><div class="field"><label>Password</label><input name="password" type="password" autocomplete="new-password" minlength="6" required></div><button class="primary">Crea account</button><button type="button" class="secondary" onclick="state.view='login';state.message='';render()">Torna al login</button></form></div></div>`}
async function signIn(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));state.message='Accesso in corso...';render();const {error}=await sb.auth.signInWithPassword({email:f.email,password:f.password});if(error) setMsg(error.message);}
async function signUpDetailed(ev){
  ev.preventDefault();
  const f=Object.fromEntries(new FormData(ev.target));
  if(!f.email||!f.password||!f.first_name||!f.last_name||!f.company_name||!f.vat_number) return setMsg('Compila tutti i campi.');
  state.message='Creazione account in corso...';render();
  const {data:authData,error}=await sb.auth.signUp({
    email:f.email,
    password:f.password,
    options:{data:{first_name:f.first_name,last_name:f.last_name,company_name:f.company_name,vat_number:f.vat_number,email:f.email}}
  });
  if(error) return setMsg(error.message);
  if(authData.user){
    // Salva sempre il profilo utente appena l'account viene creato.
    // Dopo la registrazione TOTIME torna al login: l'utente deve accedere con le credenziali scelte.
    const {error:profileError}=await sb.from('user_profiles').upsert({
      user_id:authData.user.id,
      first_name:f.first_name,
      last_name:f.last_name,
      company_name:f.company_name,
      vat_number:f.vat_number,
      email:f.email
    },{onConflict:'user_id'});
    if(profileError) return setMsg('Account creato, ma profilo non salvato: '+profileError.message);
  }
  if(authData.session){
    await sb.auth.signOut();
  }
  data={clients:[],projects:[],activities:[],entries:[],monthly:[],billingHeaders:[],profiles:[]};
  session=null;
  state.view='login';
  state.message='Account creato correttamente. Ora accedi con email e password.';
  render();
}
async function signUpFromForm(form){state.view='register';render()}
async function logout(){await sb.auth.signOut()}

function home(){const t=totals();return appShell(`<div class="hello">Ciao Giovanni</div>${monthSelector()}<div class="card total"><div class="sub">Totale mese</div><div class="amount">${fmtEUR(t.amount)}</div><div class="meta"><span>${fmtNum(t.hours,1)} h</span><span>${fmtNum(t.days,1)} gg/u</span></div></div><div class="grid"><button class="primary wide" onclick="newEntryChoice()">+ Nuovo consuntivo</button><button class="menuBtn" onclick="go('timesheet')">🗓 Timesheet <span>›</span></button><button class="menuBtn" onclick="go('summary')">📊 Riepilogo <span>›</span></button><button class="menuBtn" onclick="go('billing')">🧾 Fatturazione <span>›</span></button><button class="menuBtn" onclick="go('settings')">⚙️ Configurazione <span>›</span></button></div>`)}
function newEntryChoice(){state.view='newChoice';render()}
function newChoice(){return appShell(`<h1>Nuovo consuntivo</h1><p class="sub">Cosa vuoi registrare?</p><div class="grid"><button class="menuBtn" onclick="state.view='dailyForm';render()"><span><b>Consuntivo giornaliero</b><br><span class='sub'>Ore su tariffa giornaliera 8h</span></span><span>›</span></button><button class="menuBtn" onclick="state.view='monthlyForm';render()"><span><b>Compenso mensile</b><br><span class='sub'>Una tantum senza ore e giorni</span></span><span>›</span></button></div>`)}
function sediOptions(selected=''){const sedi=['Remoto','Casa','Ufficio','Sede cliente','Onsite cliente','Altro'];return `<option></option>${sedi.map(x=>`<option value="${esc(x)}" ${x===selected?'selected':''}>${esc(x)}</option>`).join('')}`}
function projectOptions(clientId,selected=''){return `<option value=""></option>${data.projects.filter(p=>p.active&&p.client_id===clientId).map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${esc(p.name)}</option>`).join('')}`}
function activityOptions(selected=''){return `<option value=""></option>${data.activities.filter(a=>a.active).map(a=>`<option value="${a.id}" ${a.id===selected?'selected':''}>${esc(a.name)}</option>`).join('')}`}
function refreshProjectsForForm(form){const client=form.client_id.value;const project=form.project_id;project.innerHTML=projectOptions(client,'')}
function dailyForm(){const clients=data.clients.filter(c=>c.compensation_type==='daily_rate_8h'&&c.active);const selected=clients[0]?.id||'';return appShell(`<h1>Consuntivo giornaliero</h1>${clients.length?`<form class="form" onsubmit="saveDaily(event)"><div class="field"><label>Data</label><input name="entry_date" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Cliente</label><select name="client_id" onchange="refreshProjectsForForm(this.form)">${clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Cliente/Progetto</label><select name="project_id">${projectOptions(selected)}</select></div><div class="field"><label>Attività</label><select name="activity_id">${activityOptions()}</select></div><div class="field"><label>Luogo di lavoro / Sede</label><select name="work_location">${sediOptions()}</select></div><div class="field"><label>Descrizione</label><textarea name="description"></textarea></div><div class="field"><label>Ore consuntivate</label><input name="hours" type="number" step="0.25" value="8"></div><div class="field"><label>Note</label><textarea name="notes" placeholder="Note interne opzionali"></textarea></div><div class="actions"><button class="primary">Salva</button><button type="button" class="secondary" onclick="go('home')">Annulla</button></div></form>`:`<div class="card">Crea prima un cliente con tariffa giornaliera in Configurazione.</div>`}`)}
async function saveDaily(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const c=clientById(f.client_id);const payload={entry_date:f.entry_date,client_id:f.client_id,project_id:f.project_id||null,activity_id:f.activity_id||null,work_location:norm(f.work_location)||null,description:f.description||null,notes:f.notes||null,hours:Number(f.hours||0),daily_rate_snapshot:Number(c?.daily_rate||0),standard_hours_snapshot:Number(c?.standard_hours||8)};const {error}=await sb.from('timesheet_entries').insert(payload);if(error) return setMsg(error.message);await reload();state.view='timesheet';render()}
function dailyEdit(){const e=data.entries.find(x=>x.id===state.edit);if(!e)return timesheet();const clients=data.clients.filter(c=>c.compensation_type==='daily_rate_8h'&&c.active);return appShell(`<h1>Modifica consuntivo</h1><form class="form" onsubmit="saveDailyEdit(event)"><div class="field"><label>Data</label><input name="entry_date" type="date" value="${esc(e.entry_date)}"></div><div class="field"><label>Cliente</label><select name="client_id" onchange="refreshProjectsForForm(this.form)">${clients.map(c=>`<option value="${c.id}" ${c.id===e.client_id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Cliente/Progetto</label><select name="project_id">${projectOptions(e.client_id,e.project_id||'')}</select></div><div class="field"><label>Attività</label><select name="activity_id">${activityOptions(e.activity_id||'')}</select></div><div class="field"><label>Luogo di lavoro / Sede</label><select name="work_location">${sediOptions(e.work_location||'')}</select></div><div class="field"><label>Descrizione</label><textarea name="description">${esc(e.description||'')}</textarea></div><div class="field"><label>Ore consuntivate</label><input name="hours" type="number" step="0.25" value="${Number(e.hours||0)}"></div><div class="field"><label>Note</label><textarea name="notes" placeholder="Note interne opzionali">${esc(e.notes||'')}</textarea></div><div class="actions"><button class="primary">Salva modifiche</button><button type="button" class="secondary" onclick="duplicateDaily('${e.id}')">Duplica</button><button type="button" class="secondary danger" onclick="deleteDaily('${e.id}')">Elimina</button><button type="button" class="secondary" onclick="go('timesheet')">Annulla</button></div></form>`)}
async function saveDailyEdit(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const c=clientById(f.client_id);const payload={entry_date:f.entry_date,client_id:f.client_id,project_id:f.project_id||null,activity_id:f.activity_id||null,work_location:norm(f.work_location)||null,description:f.description||null,notes:f.notes||null,hours:Number(f.hours||0),daily_rate_snapshot:Number(c?.daily_rate||0),standard_hours_snapshot:Number(c?.standard_hours||8)};const {error}=await sb.from('timesheet_entries').update(payload).eq('id',state.edit);if(error)return setMsg(error.message);await reload();state.view='timesheet';state.edit=null;render()}
async function duplicateDaily(idv){const e=data.entries.find(x=>x.id===idv);if(!e)return;const copy={entry_date:new Date().toISOString().slice(0,10),client_id:e.client_id,project_id:e.project_id,activity_id:e.activity_id,work_location:e.work_location,description:e.description,notes:e.notes,hours:e.hours,daily_rate_snapshot:e.daily_rate_snapshot,standard_hours_snapshot:e.standard_hours_snapshot};const {error}=await sb.from('timesheet_entries').insert(copy);if(error)return setMsg(error.message);await reload();state.view='timesheet';render()}
async function deleteDaily(idv){if(!confirm('Eliminare questo consuntivo?'))return;const {error}=await sb.from('timesheet_entries').delete().eq('id',idv);if(error)return setMsg(error.message);await reload();state.view='timesheet';render()}

function monthlyForm(){const clients=data.clients.filter(c=>c.compensation_type==='monthly_flat'&&c.active);const selected=clients[0]?.id||'';return appShell(`<h1>Compenso mensile</h1>${clients.length?`<form class="form" onsubmit="saveMonthly(event)"><div class="field"><label>Mese</label><input name="month" type="month" value="${state.month}"></div><div class="field"><label>Cliente</label><select name="client_id" onchange="refreshProjectsForForm(this.form)">${clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Cliente/Progetto</label><select name="project_id">${projectOptions(selected)}</select></div><div class="field"><label>Descrizione</label><textarea name="description"></textarea></div><div class="field"><label>Importo</label><input name="amount" type="number" step="0.01" value="0"></div><div class="field"><label>Note</label><textarea name="notes" placeholder="Note interne opzionali"></textarea></div><div class="actions"><button class="primary">Salva</button><button type="button" class="secondary" onclick="go('home')">Annulla</button></div></form>`:`<div class="card">Crea prima un cliente una tantum mensile in Configurazione.</div>`}`)}
async function saveMonthly(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const [year,month]=String(f.month||state.month).split('-').map(Number);const payload={year,month,client_id:f.client_id,project_id:f.project_id||null,description:f.description||null,notes:f.notes||null,amount:Number(f.amount||0)};const {error}=await sb.from('monthly_compensations').insert(payload);if(error)return setMsg(error.message);await reload();state.view='timesheet';render()}
function monthlyEdit(){const m=data.monthly.find(x=>x.id===state.edit);if(!m)return timesheet();const clients=data.clients.filter(c=>c.compensation_type==='monthly_flat'&&c.active);const mm=`${m.year}-${String(m.month).padStart(2,'0')}`;return appShell(`<h1>Modifica compenso mensile</h1><form class="form" onsubmit="saveMonthlyEdit(event)"><div class="field"><label>Mese</label><input name="month" type="month" value="${mm}"></div><div class="field"><label>Cliente</label><select name="client_id" onchange="refreshProjectsForForm(this.form)">${clients.map(c=>`<option value="${c.id}" ${c.id===m.client_id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Cliente/Progetto</label><select name="project_id">${projectOptions(m.client_id,m.project_id||'')}</select></div><div class="field"><label>Descrizione</label><textarea name="description">${esc(m.description||'')}</textarea></div><div class="field"><label>Importo</label><input name="amount" type="number" step="0.01" value="${Number(m.amount||0)}"></div><div class="field"><label>Note</label><textarea name="notes" placeholder="Note interne opzionali">${esc(m.notes||'')}</textarea></div><div class="actions"><button class="primary">Salva modifiche</button><button type="button" class="secondary" onclick="duplicateMonthly('${m.id}')">Duplica</button><button type="button" class="secondary danger" onclick="deleteMonthly('${m.id}')">Elimina</button><button type="button" class="secondary" onclick="go('timesheet')">Annulla</button></div></form>`)}
async function saveMonthlyEdit(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const [year,month]=String(f.month||state.month).split('-').map(Number);const payload={year,month,client_id:f.client_id,project_id:f.project_id||null,description:f.description||null,notes:f.notes||null,amount:Number(f.amount||0)};const {error}=await sb.from('monthly_compensations').update(payload).eq('id',state.edit);if(error)return setMsg(error.message);await reload();state.view='timesheet';state.edit=null;render()}
async function duplicateMonthly(idv){const m=data.monthly.find(x=>x.id===idv);if(!m)return;const {year,month}=periodParts();const copy={year,month,client_id:m.client_id,project_id:m.project_id,description:m.description,notes:m.notes,amount:m.amount};const {error}=await sb.from('monthly_compensations').insert(copy);if(error)return setMsg(error.message);await reload();state.view='timesheet';render()}
async function deleteMonthly(idv){if(!confirm('Eliminare questo compenso mensile?'))return;const {error}=await sb.from('monthly_compensations').delete().eq('id',idv);if(error)return setMsg(error.message);await reload();state.view='timesheet';render()}

function editEntry(id,type){state.edit=id;state.view=type==='monthly'?'monthlyEdit':'dailyEdit';render()}
function timesheet(){const rows=rowsForMonth().map(e=>({...e,kind:'daily'})).concat(monthlyRows().map(m=>({...m,kind:'monthly'}))).sort((a,b)=>{const da=a.kind==='daily'?a.entry_date:`${a.year}-${String(a.month).padStart(2,'0')}-01`;const db=b.kind==='daily'?b.entry_date:`${b.year}-${String(b.month).padStart(2,'0')}-01`;return db.localeCompare(da)});const t=totals();return appShell(`<h1>Timesheet</h1>${monthSelector()}<div class="card"><b>Totale operativo</b><div class="sub">${fmtNum(t.hours,1)} h · ${fmtNum(t.days,1)} gg/u</div></div><button class="primary" onclick="newEntryChoice()">+ Nuovo consuntivo</button><div class="list">${rows.map(r=>r.kind==='daily'?`<div class="row" onclick="editEntry('${r.id}','daily')"><div class="date">${String(r.entry_date).slice(8,10)}/${String(r.entry_date).slice(5,7)}</div><div><div class="title">${esc(clientName(r.client_id))}${projectName(r.project_id)?' / '+esc(projectName(r.project_id)):''}</div><div class="desc">${esc(activityName(r.activity_id)||'')} ${r.work_location?'· '+esc(r.work_location):''}</div><div class="desc">${esc(r.description||'')}</div>${r.notes?`<div class="desc">Note: ${esc(r.notes)}</div>`:''}</div><div class="value">${fmtNum(r.hours,1)} h</div></div>`:`<div class="row" onclick="editEntry('${r.id}','monthly')"><div class="date">${String(r.month).padStart(2,'0')}/${r.year}</div><div><div class="title">${esc(clientName(r.client_id))}${projectName(r.project_id)?' / '+esc(projectName(r.project_id)):''}</div><div class="desc">Una tantum mensile</div><div class="desc">${esc(r.description||'')}</div>${r.notes?`<div class="desc">Note: ${esc(r.notes)}</div>`:''}</div><div class="value">Una tantum</div></div>`).join('')||'<div class="empty">Nessun consuntivo nel mese.</div>'}</div>`)}
function summary(){const groups=groupSummary();const t=totals();return appShell(`<h1>Riepilogo</h1>${monthSelector()}<div class="card"><b>Totale mese</b><div class="metricLine">${metricLine(t.hours,t.amount)}</div></div><div class="list">${groups.map(r=>`<div class="row summaryRow"><div></div><div><div class="title">${esc(clientName(r.client_id))}</div><div class="desc">${esc(projectName(r.project_id)||'Senza progetto')}</div><div class="metricLine">${r.type==='daily'?metricLine(r.hours,r.amount):monthlyMetricLine(r.amount)}</div></div><div class="value"></div></div>`).join('')||'<div class="empty">Nessun riepilogo.</div>'}</div>`)}
function billingGroupsByClient(){const lines=groupSummary();const by={};lines.forEach(l=>{if(!by[l.client_id])by[l.client_id]={client_id:l.client_id,lines:[],total:0,hours:0};by[l.client_id].lines.push(l);by[l.client_id].total+=Number(l.amount||0);by[l.client_id].hours+=Number(l.hours||0)});return Object.values(by).sort((a,b)=>clientName(a.client_id).localeCompare(clientName(b.client_id)))}
function billing(){const groups=billingGroupsByClient();const total=groups.reduce((s,g)=>s+g.total,0);return appShell(`<h1>Fatturazione</h1>${monthSelector()}<div class="card"><b>Totale fatturazione mese</b><div class="amount" style="font-size:30px;margin-top:8px">${fmtEUR(total)}</div><div class="sub">Una fattura mensile per cliente</div></div><div class="list">${groups.map(g=>{const st=headerStatus(g.client_id);return `<div class="row" onclick="openBillingClient('${g.client_id}')"><div></div><div><div class="title">${esc(clientName(g.client_id))}</div><div class="metricLine">${metricLine(g.hours,g.total)}</div><span class="tag ${statusClass(st)}">${statusLabel(st)}</span></div><div class="value">›</div></div>`}).join('')||'<div class="empty">Nessuna riga fatturabile.</div>'}</div>`)}
function openBillingClient(clientId){state.edit=clientId;state.view='billingDetail';render()}
function billingDetailView(){const clientId=state.edit;const group=billingGroupsByClient().find(g=>g.client_id===clientId);if(!group)return billing();const header=headerForClient(clientId);const st=header?.status||'to_invoice';return appShell(`<h1>${esc(clientName(clientId))}</h1><p class="sub">Fattura ${monthLabel(state.month)}</p><div class="card"><b>Totale cliente</b><div class="amount" style="font-size:32px;margin-top:8px">${fmtEUR(group.total)}</div><div class="metricLine">${metricLine(group.hours,group.total)}</div><span class="tag ${statusClass(st)}">${statusLabel(st)}</span></div><h2>Righe Fiscozen</h2><div class="list">${group.lines.map((l,i)=>`<div class="row"><div>${i+1}</div><div><div class="title">${esc(projectName(l.project_id)||'Senza progetto')}</div><div class="metricLine">${l.type==='daily'?metricLine(l.hours,l.amount):monthlyMetricLine(l.amount)}</div><div class="copybox" id="copy-${i}">${esc(fiscoText(l))}</div><button class="secondary" onclick="copyText('${esc(fiscoText(l)).replace(/'/g,'&#39;')}')">Copia descrizione</button></div><div></div></div>`).join('')}</div><h2>Dati fattura / incasso</h2><form class="form" onsubmit="saveBillingHeader(event)"><div class="field"><label>Stato</label><select name="status"><option value="to_invoice" ${st==='to_invoice'?'selected':''}>Da fatturare</option><option value="invoice_issued" ${st==='invoice_issued'?'selected':''}>Fattura emessa</option><option value="collected" ${st==='collected'?'selected':''}>Incassato</option><option value="excluded" ${st==='excluded'?'selected':''}>Escluso</option></select></div><div class="field"><label>Numero fattura</label><input name="invoice_number" value="${esc(header?.invoice_number||'')}"></div><div class="field"><label>Data fattura</label><input name="invoice_date" type="date" value="${esc(header?.invoice_date||'')}"></div><div class="field"><label>Data incasso</label><input name="collection_date" type="date" value="${esc(header?.collection_date||'')}"></div><div class="field"><label>Importo incassato</label><input name="collected_amount" type="number" step="0.01" value="${Number(header?.collected_amount||0)}"></div><div class="field"><label>Note</label><textarea name="notes">${esc(header?.notes||'')}</textarea></div><div class="actions"><button class="primary">Salva stato fattura</button><button type="button" class="secondary" onclick="go('billing')">Indietro</button></div></form>`)}
async function saveBillingHeader(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const clientId=state.edit;const group=billingGroupsByClient().find(g=>g.client_id===clientId);const {year,month}=periodParts();const payload={year,month,client_id:clientId,total_amount:Number(group?.total||0),status:f.status,invoice_number:norm(f.invoice_number)||null,invoice_date:f.invoice_date||null,collection_date:f.collection_date||null,collected_amount:Number(f.collected_amount||0)||null,notes:f.notes||null};const existing=headerForClient(clientId);let error;if(existing){({error}=await sb.from('billing_headers').update(payload).eq('id',existing.id));}else{({error}=await sb.from('billing_headers').insert(payload));}if(error)return setMsg(error.message);await reload();state.view='billingDetail';state.edit=clientId;render()}
function copyText(txt){const cleaned=document.createElement('textarea');cleaned.innerHTML=txt;const val=cleaned.value;navigator.clipboard?.writeText(val).then(()=>setMsg('Descrizione copiata.')).catch(()=>prompt('Copia descrizione:',val))}

function settings(){return appShell(`<h1>Configurazione</h1><div class="list"><div class="row" onclick="go('clients')"><div>👤</div><div><div class="title">Clienti</div><div class="desc">Tariffe e tipo compenso</div></div><div>›</div></div><div class="row" onclick="go('projects')"><div>📁</div><div><div class="title">Progetti / Clienti finali</div><div class="desc">Collegati al cliente principale</div></div><div>›</div></div><div class="row" onclick="go('activities')"><div>🏷️</div><div><div class="title">Attività</div><div class="desc">PM, AMS, Gestione...</div></div><div>›</div></div><div class="row"><div>☁️</div><div><div class="title">Database</div><div class="desc">Supabase PostgreSQL · ${esc(session?.user?.email||'')}</div></div><div></div></div></div><div class="grid"><button class="secondary" onclick="exportData()">Export JSON</button><label class="secondary" style="display:block;text-align:center;cursor:pointer">Importa CSV<input type="file" accept=".csv,text/csv" style="display:none" onchange="importCsv(event)"></label><button class="secondary" onclick="reload()">Ricarica da database</button><button class="secondary danger" onclick="logout()">Esci</button></div>`)}
function clients(){return appShell(`<h1>Clienti</h1><form class="form" onsubmit="addClient(event)"><div class="field"><label>Nome cliente</label><input name="name" required></div><div class="field"><label>Tipo compenso</label><select name="compensation_type"><option value="daily_rate_8h">Tariffa giornaliera 8h</option><option value="monthly_flat">Una tantum mensile</option></select></div><div class="field"><label>Tariffa giornaliera</label><input name="daily_rate" type="number" step="0.01" value="0"></div><button class="primary">Aggiungi cliente</button></form><div class="list">${data.clients.map(c=>`<div class="row" onclick="editClient('${c.id}')"><div></div><div><div class="title">${esc(c.name)}</div><div class="desc">${c.compensation_type==='daily_rate_8h'?'Tariffa giornaliera 8h · '+fmtEUR(c.daily_rate||0):'Una tantum mensile'} · ${c.active?'Attivo':'Disattivo'}</div></div><div>›</div></div>`).join('')||'<div class="empty">Nessun cliente.</div>'}</div>`)}
function editClient(id){state.edit=id;state.view='clientEdit';render()}
function clientEdit(){const c=clientById(state.edit);if(!c)return clients();return appShell(`<h1>Modifica cliente</h1><form class="form" onsubmit="saveClient(event)"><div class="field"><label>Nome cliente</label><input name="name" value="${esc(c.name)}" required></div><div class="field"><label>Tipo compenso</label><select name="compensation_type"><option value="daily_rate_8h" ${c.compensation_type==='daily_rate_8h'?'selected':''}>Tariffa giornaliera 8h</option><option value="monthly_flat" ${c.compensation_type==='monthly_flat'?'selected':''}>Una tantum mensile</option></select></div><div class="field"><label>Tariffa giornaliera</label><input name="daily_rate" type="number" step="0.01" value="${Number(c.daily_rate||0)}"></div><div class="field"><label>Ore standard giornata</label><input name="standard_hours" type="number" step="0.25" value="${Number(c.standard_hours||8)}"></div><div class="field"><label>Attivo</label><select name="active"><option value="true" ${c.active?'selected':''}>Sì</option><option value="false" ${!c.active?'selected':''}>No</option></select></div><div class="actions"><button class="primary">Salva modifiche</button><button type="button" class="secondary danger" onclick="deleteClient('${c.id}')">Elimina cliente</button><button type="button" class="secondary" onclick="go('clients')">Annulla</button></div></form>`)}
async function addClient(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const payload={name:norm(f.name),compensation_type:f.compensation_type,daily_rate:Number(f.daily_rate||0),standard_hours:8,active:true};const {error}=await sb.from('clients').insert(payload);if(error)return setMsg(error.message);await reload();state.view='clients';render()}
async function saveClient(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const payload={name:norm(f.name),compensation_type:f.compensation_type,daily_rate:Number(f.daily_rate||0),standard_hours:Number(f.standard_hours||8),active:f.active==='true'};const {error}=await sb.from('clients').update(payload).eq('id',state.edit);if(error)return setMsg(error.message);await reload();state.view='clients';state.edit=null;render()}
async function deleteClient(idv){if(!confirm('Eliminare il cliente? Se esistono consuntivi collegati, il database potrebbe bloccare la cancellazione. In quel caso usa Disattivo.'))return;const {error}=await sb.from('clients').delete().eq('id',idv);if(error)return setMsg(error.message);await reload();state.view='clients';render()}
function projects(){return appShell(`<h1>Progetti / Clienti finali</h1><form class="form" onsubmit="addProject(event)"><div class="field"><label>Cliente collegato</label><select name="client_id">${data.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Nome progetto / cliente finale</label><input name="name" required></div><button class="primary">Aggiungi progetto</button></form><div class="list">${data.projects.map(p=>`<div class="row" onclick="editProject('${p.id}')"><div></div><div><div class="title">${esc(clientName(p.client_id))}</div><div class="desc">${esc(p.name)} · ${p.active?'Attivo':'Disattivo'}</div></div><div>›</div></div>`).join('')||'<div class="empty">Nessun progetto.</div>'}</div>`)}
function editProject(id){state.edit=id;state.view='projectEdit';render()}
function projectEdit(){const p=projectById(state.edit);if(!p)return projects();return appShell(`<h1>Modifica progetto</h1><form class="form" onsubmit="saveProject(event)"><div class="field"><label>Cliente collegato</label><select name="client_id">${data.clients.map(c=>`<option value="${c.id}" ${c.id===p.client_id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Nome progetto / cliente finale</label><input name="name" value="${esc(p.name)}" required></div><div class="field"><label>Attivo</label><select name="active"><option value="true" ${p.active?'selected':''}>Sì</option><option value="false" ${!p.active?'selected':''}>No</option></select></div><div class="actions"><button class="primary">Salva modifiche</button><button type="button" class="secondary danger" onclick="deleteProject('${p.id}')">Elimina progetto</button><button type="button" class="secondary" onclick="go('projects')">Annulla</button></div></form>`)}
async function addProject(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const {error}=await sb.from('projects').insert({client_id:f.client_id,name:norm(f.name),active:true});if(error)return setMsg(error.message);await reload();state.view='projects';render()}
async function saveProject(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const {error}=await sb.from('projects').update({client_id:f.client_id,name:norm(f.name),active:f.active==='true'}).eq('id',state.edit);if(error)return setMsg(error.message);await reload();state.view='projects';state.edit=null;render()}
async function deleteProject(idv){if(!confirm('Eliminare il progetto? Se esistono consuntivi collegati, il database potrebbe bloccare la cancellazione.'))return;const {error}=await sb.from('projects').delete().eq('id',idv);if(error)return setMsg(error.message);await reload();state.view='projects';render()}
function activities(){return appShell(`<h1>Attività</h1><form class="form" onsubmit="addActivity(event)"><div class="field"><label>Nome attività</label><input name="name" required></div><button class="primary">Aggiungi attività</button></form><div class="list">${data.activities.map(a=>`<div class="row" onclick="editActivity('${a.id}')"><div></div><div><div class="title">${esc(a.name)}</div><div class="desc">${a.active?'Attiva':'Disattiva'}</div></div><div>›</div></div>`).join('')||'<div class="empty">Nessuna attività.</div>'}</div>`)}
function editActivity(id){state.edit=id;state.view='activityEdit';render()}
function activityEdit(){const a=activityById(state.edit);if(!a)return activities();return appShell(`<h1>Modifica attività</h1><form class="form" onsubmit="saveActivity(event)"><div class="field"><label>Nome attività</label><input name="name" value="${esc(a.name)}" required></div><div class="field"><label>Attiva</label><select name="active"><option value="true" ${a.active?'selected':''}>Sì</option><option value="false" ${!a.active?'selected':''}>No</option></select></div><div class="actions"><button class="primary">Salva modifiche</button><button type="button" class="secondary danger" onclick="deleteActivity('${a.id}')">Elimina attività</button><button type="button" class="secondary" onclick="go('activities')">Annulla</button></div></form>`)}
async function addActivity(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const {error}=await sb.from('activities').insert({name:norm(f.name),active:true});if(error)return setMsg(error.message);await reload();state.view='activities';render()}
async function saveActivity(ev){ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target));const {error}=await sb.from('activities').update({name:norm(f.name),active:f.active==='true'}).eq('id',state.edit);if(error)return setMsg(error.message);await reload();state.view='activities';state.edit=null;render()}
async function deleteActivity(idv){if(!confirm('Eliminare attività? Se usata nei consuntivi, il database potrebbe bloccare la cancellazione.'))return;const {error}=await sb.from('activities').delete().eq('id',idv);if(error)return setMsg(error.message);await reload();state.view='activities';render()}

async function ensureClient(name,type,rowRate=0){let c=data.clients.find(x=>x.name.toLowerCase()===name.toLowerCase());if(c)return c;const {data:rows,error}=await sb.from('clients').insert({name,compensation_type:type==='monthly'?'monthly_flat':'daily_rate_8h',daily_rate:Number(rowRate||0),standard_hours:8,active:true}).select().single();if(error)throw error;data.clients.push(rows);return rows}
async function ensureProject(clientId,name){if(!name)return null;let p=data.projects.find(x=>x.client_id===clientId&&x.name.toLowerCase()===name.toLowerCase());if(p)return p;const {data:row,error}=await sb.from('projects').insert({client_id:clientId,name,active:true}).select().single();if(error)throw error;data.projects.push(row);return row}
async function ensureActivity(name){if(!name)return null;let a=data.activities.find(x=>x.name.toLowerCase()===name.toLowerCase());if(a)return a;const {data:row,error}=await sb.from('activities').insert({name,active:true}).select().single();if(error)throw error;data.activities.push(row);return row}
function parseCsvLine(line,sep){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===sep&&!q){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out.map(x=>x.trim())}
function canonHeader(h){return String(h||'').toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\w/ ]+/g,'').replace(/\s+/g,' ')}
function parseAmount(v){return Number(String(v||'0').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''))||0}
function toDate(v){v=norm(v);if(!v)return'';if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;const m=v.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{4})$/);if(m)return`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;return''}
function toMonth(v){const d=toDate(v);if(d)return d.slice(0,7);v=norm(v);if(/^\d{4}-\d{2}$/.test(v))return v;return''}
async function importCsv(ev){const file=ev.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=async()=>{try{const text=reader.result.replace(/^\uFEFF/,'').trim();if(!text)return setMsg('CSV vuoto.');const lines=text.split(/\r?\n/).filter(Boolean);const sep=(lines[0].match(/;/g)||[]).length>=(lines[0].match(/,/g)||[]).length?';':',';const headers=parseCsvLine(lines.shift(),sep).map(canonHeader);const get=(row,names)=>{for(const n of names.map(canonHeader)){const i=headers.indexOf(n);if(i>=0)return row[i]||''}return''};let count=0;for(const line of lines){const row=parseCsvLine(line,sep);if(!row.some(x=>norm(x)))continue;const tipoRaw=get(row,['tipo','type']);const tipo=(tipoRaw||'Tariffa giornaliera 8h').toLowerCase();const cliente=norm(get(row,['cliente','client']));if(!cliente)continue;const isMonthly=tipo.includes('mens')||tipo.includes('monthly')||tipo.includes('una tantum');const ore=parseAmount(get(row,['ore','hours']));const amount=parseAmount(get(row,['importo','amount']));let rowRate=amount>0&&ore>0?amount/ore*8:0;const client=await ensureClient(cliente,isMonthly?'monthly':'daily',rowRate);if(!client.daily_rate&&rowRate>0){await sb.from('clients').update({daily_rate:rowRate}).eq('id',client.id);client.daily_rate=rowRate}const progetto=norm(get(row,['cliente/progetto','progetto','cliente finale','project']));const project=await ensureProject(client.id,progetto);const att=norm(get(row,['attività','attivita','attivit','activity']));const activity=await ensureActivity(att);const descrizione=get(row,['descrizione','description']);const luogo=norm(get(row,['luogo/sede','luogo','sede','luogo di lavoro','work location','location']));const note=get(row,['note','notes']);if(isMonthly){const mese=norm(get(row,['mese','month']))||toMonth(get(row,['data','date']))||state.month;const [year,month]=mese.split('-').map(Number);const payload={year,month,client_id:client.id,project_id:project?.id||null,description:descrizione||null,notes:note||null,amount};const {error}=await sb.from('monthly_compensations').insert(payload);if(error)throw error;count++;}else{const date=toDate(get(row,['data','date']))||new Date().toISOString().slice(0,10);const rate=rowRate||Number(client.daily_rate||0);const payload={entry_date:date,client_id:client.id,project_id:project?.id||null,activity_id:activity?.id||null,work_location:luogo||null,description:descrizione||null,notes:note||null,hours:ore,daily_rate_snapshot:rate,standard_hours_snapshot:8};const {error}=await sb.from('timesheet_entries').insert(payload);if(error)throw error;count++;}}
await fetchAll();state.view='timesheet';setMsg(`Import completato: ${count} righe salvate su Supabase.`);}catch(e){console.error(e);setMsg('Errore import CSV: '+(e.message||e));}};reader.readAsText(file,'windows-1252')}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='totime-supabase-backup.json';a.click()}
function render(){if(state.loading){document.getElementById('app').innerHTML=loadingView();return}if(!session){document.getElementById('app').innerHTML=(state.view==='register'?registerView():loginView());return}let html='';if(state.view==='home')html=home();if(state.view==='newChoice')html=newChoice();if(state.view==='dailyForm')html=dailyForm();if(state.view==='dailyEdit')html=dailyEdit();if(state.view==='monthlyForm')html=monthlyForm();if(state.view==='monthlyEdit')html=monthlyEdit();if(state.view==='timesheet')html=timesheet();if(state.view==='summary')html=summary();if(state.view==='billing')html=billing();if(state.view==='billingDetail')html=billingDetailView();if(state.view==='settings')html=settings();if(state.view==='clients')html=clients();if(state.view==='projects')html=projects();if(state.view==='activities')html=activities();if(state.view==='clientEdit')html=clientEdit();if(state.view==='projectEdit')html=projectEdit();if(state.view==='activityEdit')html=activityEdit();document.getElementById('app').innerHTML=html||home()}
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}
init();
